# Generated by Django 5.0 on 2024-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='instagram',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='twitter',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
