# Generated by Django 5.0 on 2024-02-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='ProfileBannerIMG'),
        ),
        migrations.AddField(
            model_name='profile',
            name='explanation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ProfileIMG'),
        ),
    ]
