# Generated by Django 5.0 on 2024-02-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_banner_profile_explanation_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postvideos',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
