# Generated by Django 5.0 on 2024-02-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_date_alter_postvideos_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
